### ISSUE TITLE
two tags with same rev

### ISSUE THREAD

**Issue by MilhouseVH** [kodi-pvr/pvr.pctv#63]
Tags 2.4.5-Leia and 2.4 both have rev b60b971

![s1](https://i.imgur.com/EjfkxHP.png)

Can this be fixed? There has never been a version 2.4 - if it's meant to be 2.4.0, then this is a6812224c22aaff2e70d6ec1c69a241c4605dae3 from June 2018.

**Comment by ksooo** [comment]
Removed tag 2.4.
